on:
    workflow_dispatch:
    push:
        branches: [ main, development ]

jobs:
    build:
        uses: PANiXiDA-Infrastructure/ci-cd/.github/workflows/docker-build.yml@main
        with:
          project-folder: .
          service-folder: Pl/Api
          image-tag: ${{ vars.CI_REGISTRY }}/${{ github.repository_owner }}/${{ github.repository }}:${{ github.run_number }}
        secrets:
          registry-user: ${{ secrets.REGISTRY_USER }}
          registry-token: ${{ secrets.REGISTRY_TOKEN }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
