on:
    push:
        branches: [ development ]

jobs:
    build:
        uses: PANiXiDA-Infrastructure/ci-cd/blob/main/.github/workflows/docker-build.yml@main
        with:
          project-folder: .
          service-folder: Pl/Api
          image-tag: ${{ vars.CI_REGISTRY }}/${{ vars.SERVICE_NAME }}:${{ github.run_number }}
        secrets:
          registry-user: ${{ secrets.REGISTRY_USER }}
          registry-token: ${{ secrets.REGISTRY_TOKEN }}