on:
    workflow_dispatch:
      inputs:
        publish_contracts:
          description: "Publish contracts NuGet packages"
          required: false
          default: false
          type: boolean
    pull_request:  
    push:
        branches: [ main, development ]

jobs:
  format:
    uses: PANiXiDA-Infrastructure/ci-cd/.github/workflows/dotnet-format.yml@main
    secrets:
      registry-user: ${{ secrets.REGISTRY_USER }}
      registry-token: ${{ secrets.REGISTRY_TOKEN }}

  tests:
    uses: PANiXiDA-Infrastructure/ci-cd/.github/workflows/dotnet-tests.yml@main
    secrets:
      registry-user: ${{ secrets.REGISTRY_USER }}
      registry-token: ${{ secrets.REGISTRY_TOKEN }}

  resolve-env:
    if: ${{ github.event_name != 'pull_request' }}
    uses: PANiXiDA-Infrastructure/ci-cd/.github/workflows/resolve-environment.yml@main

  build-api:
      if: ${{ github.event_name != 'pull_request' }}
      needs: [ format, tests ]
      uses: PANiXiDA-Infrastructure/ci-cd/.github/workflows/docker-build.yml@main
      with:
        service-folder: ${{ vars.API_SERVICE_FOLDER }}
        image: ${{ vars.REGISTRY_URL }}/${{ github.repository }}/${{ vars.API_SERVICE_NAME }}:${{ github.run_number }}
      secrets:
        registry-user: ${{ secrets.REGISTRY_USER }}
        registry-token: ${{ secrets.REGISTRY_TOKEN }}

  build-ui-admin:
      if: ${{ github.event_name != 'pull_request' }}
      needs: [ format, tests ]
      uses: PANiXiDA-Infrastructure/ci-cd/.github/workflows/docker-build.yml@main
      with:
        service-folder: ${{ vars.UI_ADMIN_SERVICE_FOLDER }}
        image: ${{ vars.REGISTRY_URL }}/${{ github.repository }}/${{ vars.UI_ADMIN_SERVICE_NAME }}:${{ github.run_number }}
      secrets:
        registry-user: ${{ secrets.REGISTRY_USER }}
        registry-token: ${{ secrets.REGISTRY_TOKEN }}

  update-database:
      if: ${{ github.event_name != 'pull_request' }}
      needs: [ build, resolve-env ]
      runs-on: ubuntu-latest
      environment: ${{ needs.resolve-env.outputs.environment }}
      steps:
        - uses: PANiXiDA-Infrastructure/ci-cd/.github/actions/dotnet-ef-migrator@main
          with:
            registry-user: ${{ secrets.REGISTRY_USER }}
            registry-token: ${{ secrets.REGISTRY_TOKEN }}
            env-file: ${{ secrets.BACKEND_ENV_FILE }}
            project-folder: ${{ vars.PROJECT_FOLDER }}
            migrator-folder: ${{ vars.MIGRATOR_FOLDER }}
            migrator-project: ${{ vars.MIGRATOR_PROJECT }}
            nuget-config: ${{ vars.NUGET_CONFIG }}
            nuget-provider: ${{ vars.NUGET_PROVIDER }}

  deploy-api:
    if: ${{ github.event_name != 'pull_request' }}
    needs: [ update-database, resolve-env ]
    runs-on: ubuntu-latest
    environment: ${{ needs.resolve-env.outputs.environment }}
    steps:
      - uses: PANiXiDA-Infrastructure/ci-cd/.github/actions/ssh-docker-deploy@main
        with:
          server-user: ${{ vars.SERVER_USER }}
          server-host: ${{ vars.SERVER_HOST }}
          ssh-port: ${{ vars.SERVER_SSH_PORT }}
          ssh-private-key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}

          service-folder: ${{ vars.PROJECT_FOLDER }}/${{ github.event.repository.name }}/${{ vars.API_SERVICE_NAME }}

          container-name: ${{ github.event.repository.name }}-${{ vars.API_SERVICE_NAME }}-${{ vars.ENV_SUFFIX }}
          image: ${{ vars.REGISTRY_URL }}/${{ github.repository }}/${{ vars.API_SERVICE_NAME }}:${{ github.run_number }}

          env-file: ${{ secrets.BACKEND_ENV_FILE }}

          registry-url: ${{ vars.REGISTRY_URL }}
          registry-user: ${{ secrets.REGISTRY_USER }}
          registry-token: ${{ secrets.REGISTRY_TOKEN }}

  deploy-ui-admin:
    if: ${{ github.event_name != 'pull_request' }}
    needs: [ update-database, resolve-env ]
    runs-on: ubuntu-latest
    environment: ${{ needs.resolve-env.outputs.environment }}
    steps:
      - uses: PANiXiDA-Infrastructure/ci-cd/.github/actions/ssh-docker-deploy@main
        with:
          server-user: ${{ vars.SERVER_USER }}
          server-host: ${{ vars.SERVER_HOST }}
          ssh-port: ${{ vars.SERVER_SSH_PORT }}
          ssh-private-key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}

          service-folder: ${{ vars.PROJECT_FOLDER }}/${{ github.event.repository.name }}/${{ vars.UI_ADMIN_SERVICE_NAME }}

          container-name: ${{ github.event.repository.name }}-${{ vars.UI_ADMIN_SERVICE_NAME }}-${{ vars.ENV_SUFFIX }}
          image: ${{ vars.REGISTRY_URL }}/${{ github.repository }}/${{ vars.UI_ADMIN_SERVICE_NAME }}:${{ github.run_number }}

          env-file: ${{ secrets.FRONTEND_ENV_FILE }}

          registry-url: ${{ vars.REGISTRY_URL }}
          registry-user: ${{ secrets.REGISTRY_USER }}
          registry-token: ${{ secrets.REGISTRY_TOKEN }}

  notify:
    if: ${{ always() && github.event_name != 'pull_request' }}
    needs: [ deploy ]
    uses: PANiXiDA-Infrastructure/ci-cd/.github/workflows/notify-telegram.yml@main
    with:
      event-name: ${{ github.event_name }}    
    secrets:
      telegram-bot-token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      telegram-chat-id: ${{ vars.TELEGRAM_CHAT_ID }}
      github-token: ${{ secrets.REGISTRY_TOKEN }}

  publish-contracts:
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.publish_contracts }}
    uses: PANiXiDA-Infrastructure/ci-cd/.github/workflows/dotnet-publish-github-nuget.yml@main
    with:
      project_folder: ${{ vars.NUGET_PROJECT }}
    secrets:
      GH_PACKAGES_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
      