on:
    workflow_dispatch:
    pull_request:  
    push:
        branches: [ main, development ]

jobs:
  format:
    uses: PANiXiDA-Infrastructure/ci-cd/.github/workflows/dotnet-format.yml@main
    secrets:
      registry-user: ${{ secrets.REGISTRY_USER }}
      registry-token: ${{ secrets.REGISTRY_TOKEN }}

  tests:
    uses: PANiXiDA-Infrastructure/ci-cd/.github/workflows/dotnet-tests.yml@main
    secrets:
      registry-user: ${{ secrets.REGISTRY_USER }}
      registry-token: ${{ secrets.REGISTRY_TOKEN }}

  resolve-env:
    if: ${{ github.event_name != 'pull_request' }}
    uses: PANiXiDA-Infrastructure/ci-cd/.github/workflows/resolve-environment.yml@main

  build:
      if: ${{ github.event_name != 'pull_request' }}
      needs: [ format, tests ]
      uses: PANiXiDA-Infrastructure/ci-cd/.github/workflows/docker-build.yml@main
      with:
        service-folder: ${{ vars.SERVICE_FOLDER }}
        image: ${{ vars.REGISTRY_URL }}/${{ github.repository }}/${{ vars.SERVICE_NAME }}:${{ github.run_number }}
      secrets:
        registry-user: ${{ secrets.REGISTRY_USER }}
        registry-token: ${{ secrets.REGISTRY_TOKEN }}

  update-database:
      if: ${{ github.event_name != 'pull_request' }}
      needs: [ build, resolve-env ]
      runs-on: ubuntu-latest
      environment: ${{ needs.resolve-env.outputs.environment }}
      steps:
        - uses: PANiXiDA-Infrastructure/ci-cd/.github/actions/dotnet-ef-migrator@main
          with:
            registry-user: ${{ secrets.REGISTRY_USER }}
            registry-token: ${{ secrets.REGISTRY_TOKEN }}
            env-file: ${{ secrets.ENV_FILE }}
            project-folder: ${{ vars.PROJECT_FOLDER }}
            migrator-folder: ${{ vars.MIGRATOR_FOLDER }}
            migrator-project: ${{ vars.MIGRATOR_PROJECT }}
            nuget-config: ${{ vars.NUGET_CONFIG }}
            nuget-provider: ${{ vars.NUGET_PROVIDER }}

  deploy:
    if: ${{ github.event_name != 'pull_request' }}
    needs: [ update-database, resolve-env ]
    runs-on: ubuntu-latest
    environment: ${{ needs.resolve-env.outputs.environment }}
    steps:
      - uses: PANiXiDA-Infrastructure/ci-cd/.github/actions/ssh-docker-deploy@main
        with:
          server-user: ${{ vars.SERVER_USER }}
          server-host: ${{ vars.SERVER_HOST }}
          ssh-port: ${{ vars.SERVER_SSH_PORT }}
          ssh-private-key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}

          service-folder: ${{ vars.PROJECT_FOLDER }}/${{ github.event.repository.name }}/${{ vars.SERVICE_NAME }}

          container-name: ${{ github.event.repository.name }}-${{ vars.SERVICE_NAME }}-${{ vars.ENV_SUFFIX }}
          image: ${{ vars.REGISTRY_URL }}/${{ github.repository }}/${{ vars.SERVICE_NAME }}:${{ github.run_number }}

          env-file: ${{ secrets.ENV_FILE }}

          registry-url: ${{ vars.REGISTRY_URL }}
          registry-user: ${{ secrets.REGISTRY_USER }}
          registry-token: ${{ secrets.REGISTRY_TOKEN }}
