on:
    workflow_dispatch:
    push:
        branches: [ main, development ]

jobs:
  resolve-env:
    uses: PANiXiDA-Infrastructure/ci-cd/.github/workflows/resolve-environment.yml@main

  build:
      needs: resolve-env
      uses: PANiXiDA-Infrastructure/ci-cd/.github/workflows/docker-build.yml@main
      with:
        environment: ${{ needs.resolve-env.outputs.environment }}
        service-folder: Pl/Api
        service-name: api
      secrets:
        registry-user: ${{ secrets.REGISTRY_USER }}
        registry-token: ${{ secrets.REGISTRY_TOKEN }}
